#!/usr/bin/env python3
"""publish.py — ecosystem submission kit (MASTER GAP-B, ADR-031).

"Productivity becomes marketing": every shipped plugin should be findable in
the ecosystem's directories. The constitution (Art. I §1) draws the line —
this factory NEVER opens PRs or issues on third-party repos. So this tool
prepares everything to the repo's edge:

  1. foundry/SUBMISSIONS.md — per-target payloads: prefilled links, exact
     copy, the marketplace-add command, one blurb per published plugin.
  2. One deduped desk item asking the operator to click them.

Passive indexers already pick up `.claude-plugin/marketplace.json` (kept
valid by tools/validate.py — that half of GAP-B has shipped since genesis).
No network. Deterministic. Stdlib only.
"""
import json
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from lib import parse_front_matter  # noqa: E402
import desk  # noqa: E402

AWESOME = "https://github.com/hesreallyhim/awesome-claude-code"
DOCS = "https://code.claude.com/docs/en/discover-plugins"


def published_plugins():
    mp = json.loads((ROOT / ".claude-plugin" / "marketplace.json").read_text())
    out = []
    for entry in mp.get("plugins", []):
        rec = ROOT / "foundry" / "records" / f"{entry['name']}.md"
        meta = {}
        if rec.exists():
            meta, _ = parse_front_matter(rec.read_text())
        out.append({"name": entry["name"],
                    "title": meta.get("title", entry["name"]),
                    "one_liner": meta.get("one_liner", entry.get("description", "")),
                    "version": meta.get("version", "?"),
                    "category": meta.get("category", "?")})
    return mp.get("name", "foundry"), out


def issue_link(title, body):
    return (f"{AWESOME}/issues/new?title={urllib.parse.quote(title)}"
            f"&body={urllib.parse.quote(body)}")


def render(mp_name, plugins, cfg):
    repo = cfg.get("repo") or "GhostlyGawd/plugin-foundry"
    pages = (cfg.get("pages_url") or "").rstrip("/") or \
        "https://ghostlygawd.github.io/plugin-foundry"
    add_cmd = f"/plugin marketplace add {repo}"
    lines = [
        "# SUBMISSIONS — the ecosystem publish kit (GAP-B, generated by tools/publish.py)",
        "",
        "Constitution Art. I §1: this factory never opens PRs/issues on third-party",
        "repos. Everything below is PREPARED; the operator clicks. Each target's own",
        "intended intake is used, nothing else. Regenerate: `python3 tools/publish.py`.",
        "",
        "## Target 0 — passive indexers (already live)",
        f"`.claude-plugin/marketplace.json` is valid and versioned (the validator law);",
        f"community crawlers index marketplaces from that file automatically. Nothing to do.",
        "",
        "## Target 1 — awesome-claude-code (submission via THEIR issue intake)",
        f"Repo: {AWESOME} — use their current submission form if one exists;",
        "the prefilled link below fills a plain issue with the same content.",
        "",
    ]
    body = (f"**Marketplace:** `{add_cmd}`\n"
            f"**Live catalog:** {pages}\n"
            f"**What it is:** an autonomous Claude Code plugin foundry — the repo "
            f"invents, builds, QAs, and ships single-job plugins on a loop, governed "
            f"by a written constitution and a single-writer orchestrator; every "
            f"plugin has a public birth certificate (tested + reviewed before "
            f"publish).\n\n**The shelf right now:**\n" +
            "\n".join(f"- `{p['name']}` v{p['version']} — {p['one_liner']}"
                      for p in plugins))
    lines.append(f"[Prefilled submission issue]({issue_link('Submission: Nightshift Foundry — an autonomous plugin foundry + marketplace', body)})")
    lines += [
        "",
        "## Target 2 — Anthropic community marketplace listing",
        f"Docs + intake: {DOCS}",
        f"Submit the marketplace repo `{repo}` through the form the docs point to.",
        "This is the single biggest credibility unlock (MASTER §11).",
        "",
        "## Target 3 — the copy block (any directory that takes a blurb)",
        "```",
        f"Nightshift Foundry — the autonomous software company you can fork.",
        f"An AI-run plugin workshop in a repo: it invents, builds, tests, reviews,",
        f"and ships Claude Code plugins on a loop — governed by a constitution,",
        f"a guard, and a single-writer orchestrator. Every number it shows is",
        f"computed from its own records.",
        f"  {add_cmd}",
        f"  {pages}",
        "```",
        "",
        "## Per-plugin blurbs (for individual listings)",
        "",
    ]
    for p in plugins:
        lines.append(f"- **{p['title']}** (`/plugin install {p['name']}@{mp_name}`, "
                     f"v{p['version']}, {p['category']}) — {p['one_liner']}")
    lines.append("")
    return "\n".join(lines)


def main():
    cfg = json.loads((ROOT / "foundry" / "site-config.json").read_text())
    mp_name, plugins = published_plugins()
    out = ROOT / "foundry" / "SUBMISSIONS.md"
    out.write_text(render(mp_name, plugins, cfg))
    iid, fresh = desk.add(
        "approve",
        "submit the shelf to the ecosystem directories (GAP-B)",
        "foundry/SUBMISSIONS.md holds the prefilled links and copy for "
        "awesome-claude-code + the Anthropic community marketplace. "
        "Constitution: submissions ride each directory's own intake, "
        "operator-clicked, never a third-party PR/issue from the factory.",
        "publish-kit",
        refs=["foundry/SUBMISSIONS.md"])
    print(f"publish: wrote foundry/SUBMISSIONS.md ({len(plugins)} plugins) · "
          f"desk item {iid} {'queued' if fresh else 'already open'}")


if __name__ == "__main__":
    main()
